### ISSUE TITLE
input format

### ISSUE THREAD

**Issue by bioinfo4321** [rraadd88/beditor#10]
It is a questions/clarification and not an issue.
What should go in the column "Nucleotide mutation/amino acid mutation" in the input? Is it current nucleotide/amino acid or the desired change.  Suppose you want any change (nucleotide/amino acid) in that position, how you input be made?

**Comment by rraadd88** [comment]
Hi @bioinfo4321 , its "the desired change".
Thanks your for the question. I added the the note in that section to clarify what those columns mean. 

This information about how to make the input table is included in the documentation.
Here's a direct link to the section: https://github.com/rraadd88/beditor/blob/master/README.md#table-with-mutation-information

Best.
