### ISSUE TITLE
defining custom PAM 

### ISSUE THREAD

**Issue by bioinfo4321** [rraadd88/beditor#11]
Hi, I tried to include a new BE in dbepams.tsv, however the guide selection behavior is somewhat strange. My understanding was that a wider windows achieved by changing distance of mutation (or codon) from PAM should allow for more guides being selected. But I am observing the opposite, very few guides for test2 but a lot more for test1 (see criteria in the link below), everything else is same for the 2 beditor runs. Can you think of a reason that may be happening and how to fix it?

[link to see below table as formatted](https://postimg.cc/q6B9WNhD)

criteria                                                           test1         test2
window start                                                  3               3
window end                                                 15              15
distance of mutation from PAM: minimum     14              10
distance of mutation from PAM: maximum     18              18
distance of codon start from PAM: minimum  14              10
distance of codon start from PAM: maximum  20              20

**Comment by rraadd88** [comment]
Hi @bioinfo4321 ,
As you know, there are many factors involved in the gRNA design. So the number of gRNAs designed would differ in case-by-case manner. I would suggest having a discussion about your case over email (rohan.dandage.1@ulaval.ca) instead. Without the details, I may not be able to give any suggestions. 
If possible please send me the input files (excluding the confidential info, off-course) by email, I will try my best to offer you suggestion then.
Thanks.
[closing the issue as this is an issue related to users case.]

**Comment by bioinfo4321** [comment]
Sure, I will contact you with specific query, appreciate you looking into it. On my question on input format (input format #10), can you comment if there's is a way to allow any mutation at a given position rather than specifying desired mutation.
