### ISSUE TITLE
Does beditor only design guide on positive strand?

### ISSUE THREAD

**Issue by onebeingmay** [rraadd88/beditor#16]
Hi beditor team,
I tried designing guides using BE3 system. Here is my configuration (I chose BE3 in the GUI):
```
BE editing window:
- - 4
  - 8
BE name and PAM:
- - xBE3
  - NG
BE names:
- xBE3
BE type:
- - C
  - T
PAMs:
- NG
cores: 24
custom BE and PAM: false
dinp: beditor_input.tsv
genomeassembly: GRCh38
genomerelease: 95
gui: false
host: Homo sapiens
keep_mutation_nonsense: true
make_control_neg: true
make_control_pos: true
mutation_format: nucleotide
mutation_type: null
mutations: mutations
reverse_mutations: false
step2ignore: 4
```
In the result tsv I only see guides designed for C>T mutation, which makes sense as BE3 can only convert C to T. But BE3 should also be able to convert G to A if the C>T happens on the negative strand? Does beditor only design guide on positive strand so G>A mutations on positive strand won't be covered by BE3 system?

Thank you!

**Comment by rraadd88** [comment]
Hi @onebeingmay , 
beditor should make the C>T mutations on the negative strand too. Probably the target sequences you are using do not contain optimal C>T on the negative strand for beditor to design guides there. On negative strand, in addition to the presence of C>T, presence of PAM and that too at an optimal distance would be needed.

**Comment by onebeingmay** [comment]
Thanks for the prompt response. I my case it only designed guides for C>T on positive strand and no guides were found for G>A on positive strand. But beditor should be able to design guides for G>A on positive strand as input if condition permits? Such as:

genome coordinate nucleotide mutation nucleotide wild-type
8:18400806-18400806+ A G
8:142915137-142915137+ A G
5:179833213-179833213+ A G

**Comment by rraadd88** [comment]
Hi @onebeingmay ,
If 'G>A on positive strand' is the condition, then the PAM position need to be considered too. 
If the PAM position would be on 3' side of the mutation site (as in the case NG PAM), it may not be the same as C>T mutation on negative strand.

**Comment by onebeingmay** [comment]
Hi @rraadd88 ,
I checked the output folder. In 03_guides/dguides.tsv I can see some guides designed to do C>T on the negative strand making G>A on the positive strand (around 50% of the guides), such as 6:146434004-146434004+|BE3|-|G:A|AGC:AAC|nucleotide|(BE3;-;@16;NGG;AGC:AAC;S:N;). But in the 05_output/doutput.tsv all the remaining guides work on the positive strand as indicated by the guide id. I feel confused. It looks like all the guides on the negative strand weren't selected.

By the way 04_offtargets folder is empty.

**Comment by rraadd88** [comment]
Hi @onebeingmay ,
Folder `03_guides` should contain all the guides that were designed and `05_output` should contain the guides that are filtered to keep only those that are potentially useful in editing. Some of the filtering criterias from the configuration might have lead to the filteration of the guides on the negative strand.  

Regarding the `04_offtargets`, I see that in your configuration you've used the option `step2ignore: 4`. This prevented the excetion of the 4th step where offtarget effects alignments are detected. 

Since it seems that you'd like to skip the step 4 anyways, so may be you could use the `03_guides` directly.

**Comment by onebeingmay** [comment]
Hi @rraadd88,
Thank you for pointing out! I didn't notice that I skipped step 4 as I used the configuration generated by GUI. I reran the program without skipping the step 4. Still all guides working on the minus strand weren't included in `05_output/doutput.tsv`. Do you have any idea based on my configuration why the program filters out all guides on the negative strand?

There are 94 positive guides and 127 negative guides in `03_guides/dguides.tsv`. And in `05_output/doutput.tsv` all 94 positive guides were retained but no negative guides.

**Comment by rraadd88** [comment]
Hi @onebeingmay ,
Thanks for pointing out. That's interesting. I just have one question to figure out what's the issue there. Do you see any of the "negative guides" in output of 4th step i.e. `04_offtargets/dofftargets.tsv`?

**Comment by onebeingmay** [comment]
Hi @rraadd88 ,
04_offtargets/dofftargets.tsv doesn't have guide id information. But it has 221 lines, which looks like the total number of guides (94 positive + 127 negative)
