### ISSUE TITLE
Preparing metadata (pyproject.toml) did not run successfully

### ISSUE THREAD

**Issue by ebrettmann** [rraadd88/beditor#19]
Hello,

I'm having trouble installing beditor. When I ran  `pip install --use-pep517 beditor` I got:

> Preparing metadata (pyproject.toml) ... error
>   error: subprocess-exited-with-error
>   
>   × Preparing metadata (pyproject.toml) did not run successfully.
>   │ exit code: 1
>   ╰─> [3 lines of output]
>       error in pandas setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
>           pytz >= 2011k
>                ~~~~~~~^
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed

This has happened using both python 3.8.16 and 3.11.3. Can you advise?

**Comment by rraadd88** [comment]
@ebrettmann, `beditor` is currently compatible with python 3.8 and 3.9. The latest version (v2) should resolve this issue.
