### ISSUE TITLE
#!/usr/bin/python  VERSUS  #!/usr/bin/env python2  (or 3)

### ISSUE THREAD

**Issue by enormandeau** [rraadd88/beditor#3]
It is better to use `#!/usr/bin/env python2` or `#!/usr/bin/env python3` so that python scripts are interpreted by the version of Python that the user is expecting. It is often not the one located in `/usr/bin`.

Also, being specific about the version (python2 vs python3) avoids some problems.

**Comment by rraadd88** [comment]
Hi @enormandeau ,
Thanks for the suggestion. Yes, it will make things easier for the users.
In the documentation, I recommend installation of virtual environment itself, so dependee python and module versions are taken care of.

I am closing this issue for now, you will be able to see the suggested changes in the next versions.
thanks.
