### ISSUE TITLE
error when run the test dataset

### ISSUE THREAD

**Issue by chengwsh** [rraadd88/beditor#4]
Hi,
The beditor is really helpful! Would you please take a look on one error which occured when I run the test dataset?

Traceback (most recent call last):
  File "/home/chengwsh/miniconda3/envs/beditor/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/chengwsh/miniconda3/envs/beditor/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/chengwsh/miniconda3/envs/beditor/lib/python3.6/site-packages/beditor/pipeline.py", line 98, in pipeline_chunks
    dseq2dmutagenesis(cfg)
  File "/home/chengwsh/miniconda3/envs/beditor/lib/python3.6/site-packages/beditor/lib/get_mutations.py", line 484, in dseq2dmutagenesis
    host=cfg['host'])
  File "/home/chengwsh/miniconda3/envs/beditor/lib/python3.6/site-packages/beditor/lib/get_mutations.py", line 317, in get_possible_mutagenesis
    dmutagenesis['nucleotide mutation: count']=[len(s) for s in dmutagenesis['nucleotide mutation']]
  File "/home/chengwsh/miniconda3/envs/beditor/lib/python3.6/site-packages/beditor/lib/get_mutations.py", line 317, in <listcomp>
    dmutagenesis['nucleotide mutation: count']=[len(s) for s in dmutagenesis['nucleotide mutation']]
TypeError: object of type 'float' has no len()
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chengwsh/miniconda3/envs/beditor/bin/beditor", line 11, in <module>
    sys.exit(main())
  File "/home/chengwsh/miniconda3/envs/beditor/lib/python3.6/site-packages/beditor/pipeline.py", line 491, in main
    test=args.test,force=args.force)
  File "/home/chengwsh/miniconda3/envs/beditor/lib/python3.6/site-packages/beditor/pipeline.py", line 425, in pipeline
    pool.map(pipeline_chunks, chunkcfgps)
  File "/home/chengwsh/miniconda3/envs/beditor/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/chengwsh/miniconda3/envs/beditor/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
TypeError: object of type 'float' has no len()
bash command error: 1
source activate beditor;cd dataset_homo_sapiens;beditor --cfg mutation_format_nucleotide_mutation_mutations_for.yml

Thank you very much!

**Comment by rraadd88** [comment]
Hi @chengwsh ,
Sorry to hear that.
I just checked the commands you used. There were no errors in my case.
Just to be sure, are you using my version of `pyensembl` (installed from https://github.com/rraadd88/pyensembl) or the main pyensembl from openvax?

Could you send me the versions of beditor and pyensembl you are using?
I will be happy to help you.
Thanks.

**Comment by chengwsh** [comment]
Dear Rohan,
Thank you for your reply.
I update the pyensembl to v1.7.3 and the beditor is v1.1.3.

But when I run the make_datasets.py pipeline, it have a new error

ValueError: Can't use reference 'GRCh38' for both Species(latin_name='homo_sapiens', synonyms=['homo_sapiens'], reference_assemblies={'GRCh38': (93, 93)}) and Species(latin_name='homo_sapiens', synonyms=['human'], reference_assemblies={'GRCh38': (76, 93), 'GRCh37': (55, 75), 'NCBI36': (54, 54)})

And when run test_datasets.py
ValueError: Species not found: saccharomyces_cerevisiae

Weisheng Cheng

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Rohan Dandage <notifications@github.com>
发送时间: Thursday, January 24, 2019 2:42:11 AM
收件人: rraadd88/beditor
抄送: chengwsh; Mention
主题: Re: [rraadd88/beditor] error when run the test dataset (#4)


Hi @chengwsh<https://github.com/chengwsh> ,
Sorry to hear that.
I just checked the commands you used. There were no errors in my case.
Just to be sure, are you using my version of pyensembl (installed from https://github.com/rraadd88/pyensembl) or the main pyensembl from openvax?

Could you send me the versions of beditor and pyensembl you are using?
I will be happy to help you.
Thanks.

Rohan

―

**Comment by chengwsh** [comment]
Thank you for replying me! 
The beditor version I used is v1.1.3. And the pyensembl is using your version of pyensembl (installed from https://github.com/rraadd88/pyensembl) 
Thank you very much!

**Comment by rraadd88** [comment]
I am not sure what's the issue in your case. 
I would suggest recreating the test datasets again. 
Also, you could send me the full traceback messages for `python make_datasets.py` and `python test_datasets.py`.

**Comment by rraadd88** [comment]
Hi @chengwsh ,
In the recent version (v1.1.4), in order to simplify usage of the program, I have implemented a minimal gui for `beditor`. You might want to give a try. May be that would help.

**Comment by chengwsh** [comment]
Hi Rohan Dandage,
Thank you very much. I have used the new version bedior.
When I use the test dataset, it can export results, but when I use my own input file, it still has error
[cid:image003.png@01D4CF68.143F53F0]


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Rohan Dandage <notifications@github.com>
发送时间: Thursday, February 28, 2019 1:27:27 AM
收件人: rraadd88/beditor
抄送: chengwsh; Mention
主题: Re: [rraadd88/beditor] error when run the test dataset (#4)


Hi @chengwsh<https://github.com/chengwsh> ,
In the recent version (v1.1.4), in order to simplify usage of the program, I have implemented a minimal gui for beditor. You might want to give a try. May be that would help.

―

**Comment by rraadd88** [comment]
HI @chengwsh , we could discuss the issue with your input file over email.

(Closing the issue.)
