### ISSUE TITLE
gRNA not identfied

### ISSUE THREAD

**Issue by herrroaa** [rraadd88/beditor#6]
Hi,

I am trying to design a gRNA for base editor SA(KKH)-BE3 (pam:NNNRRT).
The sequence flanking my SNP ( bold C) from file  01_sequences/dbedntmuts.fa  is GAAATGTTTGAGGATGACTCCT**C**GCAGCCTGGTCCCCACCCCAAT

There is a good pam sequence CCCAAT, however no gRNA was designed
There is also an error message 

`ERROR	from pipeline.py in make_outputs(..):215: output of step 2 or 3 are missing.`

Thanks
T

**Comment by rraadd88** [comment]
Hi @herrroaa ,
I wonder why that happened.
Could you send me the yaml (.yml) configuration file to have a look?
Thank you for posting this issue. 

Rohan

**Comment by herrroaa** [comment]
Hi @rraadd88 ,
Please find attached the .yml file, I just changed the extension to txt be compatible
[rs2229774.txt](https://github.com/rraadd88/beditor/files/3174404/rs2229774.txt)

Thanks for replying to the issue,
Tarek

**Comment by herrroaa** [comment]
Hi @rraadd88
Did you have time to look into the yml file?
Thanks,
Tarek

**Comment by rraadd88** [comment]
Hi @herrroaa ,
I will have a look today or over the weekends. My guess is that the the gRNAs were filtered out in the process. I will see exactly at which step that happened.
Thanks for the reminder.

**Comment by rraadd88** [comment]
Hi @herrroaa ,
As I see the sequence at the genome coordinates of the SNP `rs2229774`, it seems that the SNP is on positive strand but the sequence that you mentioned in the first comment is from negative strand.
![image](https://user-images.githubusercontent.com/9945034/58380598-fab1ab80-7f80-11e9-8cd9-c9ce6d75925a.png)
It seems to be the case of incorrect strand information in your `SNP.tsv` file.
My guess is that  `SNP.tsv` should look like this.

| genome coordinate | nucleotide mutation |
|-------------------|---------------------|
| 12:53211761-53211761+  | A                   |
| 12:53211761-53211761+  | T                   |
| 12:53211761-53211761+  | G                   |
| 12:53211761-53211761+  | C                   |

In the `nucleotide mutation` column you may wanna mention only the mutation that you'd like to create.

**Comment by herrroaa** [comment]
Hi @rraadd88 ,
I want to convert **C** to **T** for SNP rs2229774 . The C allele is located at the reverse strand to chr12.
https://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?do_not_redirect&rs=rs2229774

I tried using `12:53211761-53211761+ T` and `12:53211761-53211761- T`.

The sequence flanking my SNP from file 01_sequences/dbedntmuts.fa are 

`12:53211761-53211761+(+)	ATTGGGGTGGGGACCAGGCTGC**G**AGGAGTCATCCTCAAACATTTC
`
`12:53211761-53211761-(-)	GAAATGTTTGAGGATGACTCCT**C**GCAGCCTGGTCCCCACCCCAAT`



Both analysis gave me the same error
`beditor --cfg /Users/tarekmagdyshehatamohamed/Documents/BE/rs2229774.yml`

```
Namespace(cfg='/Users/tarekmagdyshehatamohamed/Documents/BE/rs2229774.yml', force=False, step=None, test=False)
start. log file: .log_beditor_2019_05_29_13_55_04_278247__Users_tarekmagdyshehatamohamed_Documents_BE_rs2229774.yml_None_False_False.log
/Users/tarekmagdyshehatamohamed/miniconda3/envs/beditor/lib/python3.6/site-packages/beditor/pipeline.py:245: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg=yaml.load(open(cfgp, 'r'))
2019_05_29_13_55_04_977905: processing: rs2229774
2019_05_29_13_55_05_641331: processing: 1 chunks.
/Users/tarekmagdyshehatamohamed/miniconda3/envs/beditor/lib/python3.6/site-packages/beditor/pipeline.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg=yaml.load(open(cfgp, 'r'))
2019_05_29_13_55_05_664798: processing: chunk00000001
2019_05_29_13_55_07_099245: collecting chunks
2019_05_29_13_55_07_127665: generating outputs
[2019-05-29 13:55:07,142] ERROR	from pipeline.py in make_outputs(..):215: output of step 2 or 3 are missing.
```

Thanks for your cooperation

**Comment by rraadd88** [comment]
Hi @herrroaa , 
Thanks for your patience, if you haven't figured out the issue by yourself already.
The issue was activity window, using the default activity window does not work.
I saved the guides without the filtering of based on activity window.
[test.txt](https://github.com/rraadd88/beditor/files/3387951/test.txt)

This is what you wanted I guess.
Best wishes,
-
Rohan
[Closing the issue now.]
