### ISSUE TITLE
no guide designed in the 05_output folder for test dataset

### ISSUE THREAD

**Issue by leejimmy93** [rraadd88/beditor#7]
Hi, I am now running beditor on the test dataset. It seems worked correctly by using the .yml parameter come with the test dataset. However, in the 05_output folder, there is no guide designed. Instead, it looks like this: 

genome coordinate       nucleotide mutation     nucleotide wild-type    guide: id
guide+PAM sequence      beditor score   alternate alignments count      CFD score
length of polyT stretch
0       9:34111967-34111967-    A       A                                               
1       9:34089056-34089056+    A       G                                               
2       2:50199638-50199638-    A       A                                               
3       12:33484358-33484358+   A       T                                               
4       24:22070190-22070190-   A       T     
...  (this is danio_rerio test dataset, I don't think I get the result I am expected)

Can you please give me a hint about where I am possibly wrong? Also I think it would be helpful to include the correct output file in the test_dataset so people can get an idea on whether they get beditor work or not. Thank you in advance for help!

**Comment by rraadd88** [comment]
Hi @leejimmy93, I'll get to this issue in a while. I've been strangled in some urgent stuff right now. :)
On a cursory note, I feel that there is a mismatch between the genome installed by the `pyensembl` and the one downloaded by `beditor`. This should not happen ideally, as the genome versions are assigned very strictly. But I would not rule out the possibility that there could be some discrepancies in the genome database itself.
Thanks for letting me know of this issue.
