### ISSUE TITLE
positive control

### ISSUE THREAD

**Issue by bioinfo4321** [rraadd88/beditor#8]
Hi, this is not really an issue but a question. My understanding was positive control guides would introduce non-sense mutations. However, in a run i did, it is returning a number of guides only a fraction of which are introducing non-sense mutations, rest are just regular substitutions. Is there any reason that may be happening.

Also, what would is the purpose of option "keep_mutation_nonsense" in cfg.

Thank you.

**Comment by rraadd88** [comment]
Hi @bioinfo4321 , 

`keep_mutation_nonsense` option will not filter out the non-sense mutations. This option is applicable when only the position of the mutation is provided as an input. (In such a case, `beditor` scans all the possible mutations at that position. If you wish to keep the non-sense mutations in the output, you'd need to choose `keep_mutation_nonsense`.    

As with the run of yours that produced only fraction of the gRNAs that were non-sense mutations, I'd say the design of the gRNA would depend on compatibility of the base editor you are using with the codon substitutions allowed (termed as "editibility" in the manuscript). Other major reason would be sequence context, for instance, if there are no PAM sites nearby, `beditor` won't be able to make any gRNAs.

I hope that helps.
Thank you for the question. (I will include a blurb about this in the documentation.)

**Comment by rraadd88** [comment]
[Closing the issue now ]
